model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"

[projects."/Users/shu/Documents/Projects/portfolio_backtest"]
trust_level = "trusted"

[projects."/Users/shu/Documents/Projects/chatall"]
trust_level = "trusted"

[projects."/Users/shu/Projects/HomePi"]
trust_level = "trusted"

[projects."/Users/shu/Projects/ai_stuff"]
trust_level = "trusted"

[projects."/Users/shu/Projects/Portseer"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[plugins."gmail@openai-curated"]
enabled = true

[[skills.config]]
path = "/Users/shu/.codex/skills/doc/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/shu/.codex/plugins/cache/openai-curated/gmail/f78e3ad49297672a905eb7afb6aa0cef34edc79e/skills/gmail/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/shu/.codex/skills/.system/imagegen/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/shu/.codex/plugins/cache/openai-curated/gmail/f78e3ad49297672a905eb7afb6aa0cef34edc79e/skills/gmail-inbox-triage/SKILL.md"
enabled = false
